import stylisticPlugin from '@stylistic/eslint-plugin';
import type { Linter } from 'eslint';

export const stylisticConfig: Linter.Config = {
  name: 'story/stylistic',
  plugins: { '@stylistic': stylisticPlugin },

  rules: {
    ...stylisticPlugin.configs.recommended.rules,
    // modern
    '@stylistic/indent': ['warn', 2, { SwitchCase: 1 }],
    '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
    '@stylistic/jsx-quotes': ['warn', 'prefer-single'],
    '@stylistic/quote-props': ['warn', 'as-needed'],
    '@stylistic/semi': ['warn', 'always'],
    '@stylistic/comma-dangle': ['warn', 'always-multiline'],
    '@stylistic/comma-spacing': ['warn', {
      before: false,
      after: true,
    }],
    '@stylistic/comma-style': ['warn', 'last'],
    '@stylistic/arrow-parens': ['warn', 'always'],
    '@stylistic/max-len': [
      'warn',
      {
        code: 200,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      },
    ],
    '@stylistic/block-spacing': ['warn', 'always'],
    '@stylistic/object-curly-spacing': ['warn', 'always'],
    '@stylistic/array-bracket-spacing': ['warn', 'never'],
    '@stylistic/keyword-spacing': ['warn', {
      before: true,
      after: true,
    }],
    '@stylistic/space-before-blocks': ['warn', 'always'],
    '@stylistic/space-in-parens': ['warn', 'never'],
    '@stylistic/space-infix-ops': ['warn'],
    '@stylistic/space-unary-ops': ['warn', {
      words: true,
      nonwords: false,
    }],
    '@stylistic/space-before-function-paren': [
      'warn',
      {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    '@stylistic/key-spacing': ['warn', {
      beforeColon: false,
      afterColon: true,
    }],
    '@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
    '@stylistic/array-element-newline': ['warn', 'consistent'],
    '@stylistic/padding-line-between-statements': [
      'warn',
      {
        blankLine: 'always',
        prev: 'directive',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'return',
      },
    ],
    '@stylistic/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
    '@/curly': ['warn', 'multi-line'],
    '@stylistic/operator-linebreak': ['warn', 'before', { overrides: { '=': 'none' } }],
    '@stylistic/linebreak-style': ['warn', 'unix'],
    '@stylistic/object-curly-newline': [
      'warn',
      {
        ObjectExpression: {
          minProperties: 4,
          multiline: true,
          consistent: true,
        },
        ObjectPattern: {
          minProperties: 4,
          multiline: true,
          consistent: true,
        },
        ImportDeclaration: {
          minProperties: 4,
          multiline: true,
          consistent: true,
        },
        ExportDeclaration: {
          minProperties: 4,
          multiline: true,
          consistent: true,
        },
      },
    ],
    '@stylistic/member-delimiter-style': [
      'warn',
      {
        multiline: {
          delimiter: 'semi',
          requireLast: true,
        },
        singleline: {
          delimiter: 'semi',
          requireLast: true,
        },
        multilineDetection: 'brackets',
      },
    ],
    '@stylistic/multiline-ternary': ['warn', 'always'],
    '@stylistic/jsx-wrap-multilines': [
      'warn',
      {
        arrow: 'parens-new-line',
        assignment: 'parens-new-line',
        condition: 'parens-new-line',
        declaration: 'parens-new-line',
        logical: 'parens-new-line',
        prop: 'parens-new-line',
        propertyValue: 'parens-new-line',
        return: 'parens-new-line',
      },
    ],
    '@stylistic/jsx-tag-spacing': [
      'warn',
      {
        closingSlash: 'never',
        beforeSelfClosing: 'always',
        afterOpening: 'never',
        beforeClosing: 'never',
      },
    ],
    '@stylistic/jsx-max-props-per-line': [
      'warn',
      { maximum: 1, when: 'multiline' },
    ],
    '@stylistic/jsx-indent-props': ['error', 2],
    '@stylistic/jsx-closing-bracket-location': ['warn', 'tag-aligned'],
    '@stylistic/jsx-closing-tag-location': ['warn', 'tag-aligned'],
    '@stylistic/jsx-curly-newline': [
      'warn',
      { multiline: 'consistent', singleline: 'consistent' },
    ],
    '@stylistic/jsx-curly-spacing': ['warn', 'never'],
    '@stylistic/jsx-equals-spacing': ['warn', 'never'],
    '@stylistic/jsx-first-prop-new-line': ['warn', 'multiline-multiprop'],
    '@stylistic/type-generic-spacing': 'warn',
    '@stylistic/type-annotation-spacing': [
      'warn',
      { after: true, before: false, overrides: { arrow: 'ignore' } },
    ],
    '@stylistic/template-curly-spacing': ['warn', 'never'],
    '@stylistic/rest-spread-spacing': ['warn', 'never'],
    '@stylistic/no-multi-spaces': 'warn',
    '@stylistic/no-floating-decimal': 'warn',
    '@stylistic/indent-binary-ops': ['warn', 2],
    '@stylistic/dot-location': ['warn', 'property'],
    '@stylistic/arrow-spacing': ['warn', { before: true, after: true }],
    '@stylistic/switch-colon-spacing': [
      'warn',
      { after: true, before: false },
    ],
    '@stylistic/padded-blocks': [
      'error',
      {
        blocks: 'never',
        classes: 'never',
        switches: 'never',
      },
      {
        allowSingleLineBlocks: true,
      },
    ],

    // old eslint names (for backwards compatibility)
    indent: 0,
    quotes: 0,
    'jsx-quotes': 0,
    'quote-props': 0,
    semi: 0,
    'comma-dangle': 0,
    'comma-spacing': 0,
    'comma-style': 0,
    'arrow-parens': 0,
    'max-len': 0,
    'block-spacing': 0,
    'object-curly-spacing': 0,
    'array-bracket-spacing': 0,
    'keyword-spacing': 0,
    'space-before-blocks': 0,
    'space-in-parens': 0,
    'space-infix-ops': 0,
    'space-unary-ops': 0,
    'space-before-function-paren': 0,
    'key-spacing': 0,
    'object-property-newline': 0,
    'object-curly-newline': 0,
    'array-element-newline': 0,
    'padding-line-between-statements': 0,
    'brace-style': 0,
    curly: 0,
    'operator-linebreak': 0,
    'linebreak-style': 0,
    'member-delimiter-style': 0,
    'multiline-ternary': 0,
    'template-curly-spacing': 0,
    'no-multi-spaces': 0,
    'no-floating-decimal': 0,
    'dot-location': 0,
    'arrow-spacing': 0,
    'switch-colon-spacing': 0,
    'padded-blocks': 0,

    // off conflicting typescript rules
    '@typescript-eslint/block-spacing': 0,
    '@typescript-eslint/brace-style': 0,
    '@typescript-eslint/comma-dangle': 0,
    '@typescript-eslint/comma-spacing': 0,
    '@typescript-eslint/func-call-spacing': 0,
    '@typescript-eslint/indent': 0,
    '@typescript-eslint/key-spacing': 0,
    '@typescript-eslint/keyword-spacing': 0,
    '@typescript-eslint/lines-around-comment': 0,
    '@typescript-eslint/lines-between-class-members': 0,
    '@typescript-eslint/member-delimiter-style': 0,
    '@typescript-eslint/no-extra-parens': 0,
    '@typescript-eslint/no-extra-semi': 0,
    '@typescript-eslint/object-curly-spacing': 0,
    '@typescript-eslint/padding-line-between-statements': 0,
    '@typescript-eslint/quotes': 0,
    '@typescript-eslint/semi': 0,
    '@typescript-eslint/space-before-blocks': 0,
    '@typescript-eslint/space-before-function-paren': 0,
    '@typescript-eslint/space-infix-ops': 0,
    '@typescript-eslint/type-annotation-spacing': 0,
    '@typescript-eslint/multiline-ternary': 0,

    'react/jsx-wrap-multilines': 0,
    'react/jsx-tag-spacing': 0,
    'react/jsx-max-props-per-line': 0,
    'react/jsx-sort-props': 0,
    'react/jsx-indent-props': 0,
    'react/jsx-closing-bracket-location': 0,
    'react/jsx-closing-tag-location': 0,
    'react/jsx-curly-newline': 0,
    'react/jsx-curly-spacing': 0,
    'react/jsx-equals-spacing': 0,
    'react/jsx-first-prop-new-line': 0,
  },
};
