import stylisticPlugin from '@stylistic/eslint-plugin';
import type { Linter } from 'eslint';

export const stylisticConfig: Linter.Config = {
  name: 'story/stylistic',
  plugins: { '@stylistic': stylisticPlugin },

  rules: {
    ...stylisticPlugin.configs.recommended.rules,
    // modern
    '@stylistic/indent': ['warn', 2, { SwitchCase: 1 }],
    '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
    '@stylistic/jsx-quotes': ['warn', 'prefer-single'],
    '@stylistic/quote-props': ['warn', 'as-needed'],
    '@stylistic/semi': ['warn', 'always'],
    '@stylistic/comma-dangle': ['warn', 'always-multiline'],
    '@stylistic/comma-spacing': ['warn', { before: false, after: true }],
    '@stylistic/comma-style': ['warn', 'last'],
    '@stylistic/arrow-parens': ['warn', 'always'],
    '@stylistic/max-len': [
      'warn',
      { code: 100, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true },
    ],
    '@stylistic/block-spacing': ['warn', 'always'],
    '@stylistic/object-curly-spacing': ['warn', 'always'],
    '@stylistic/array-bracket-spacing': ['warn', 'never'],
    '@stylistic/keyword-spacing': ['warn', { before: true, after: true }],
    '@stylistic/space-before-blocks': ['warn', 'always'],
    '@stylistic/space-in-parens': ['warn', 'never'],
    '@stylistic/space-infix-ops': ['warn'],
    '@stylistic/space-unary-ops': ['warn', { words: true, nonwords: false }],
    '@stylistic/space-before-function-paren': [
      'warn',
      { anonymous: 'always', named: 'never', asyncArrow: 'always' },
    ],
    '@stylistic/key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    '@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
    '@stylistic/array-element-newline': ['warn', 'consistent'],
    '@stylistic/padding-line-between-statements': [
      'warn',
      { blankLine: 'always', prev: 'directive', next: '*' },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
    '@stylistic/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
    '@/curly': ['warn', 'multi-line'],
    '@stylistic/operator-linebreak': ['warn', 'before'],
    '@stylistic/linebreak-style': ['warn', 'unix'],

    // old eslint names (for backwards compatibility)
    indent: ['warn', 2, { SwitchCase: 1 }],
    quotes: ['warn', 'single', { avoidEscape: true }],
    'jsx-quotes': ['warn', 'prefer-single'],
    'quote-props': ['warn', 'as-needed'],
    semi: ['warn', 'always'],
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['warn', { before: false, after: true }],
    'comma-style': ['warn', 'last'],
    'arrow-parens': ['warn', 'always'],
    'max-len': [
      'warn',
      { code: 100, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true },
    ],
    'block-spacing': ['warn', 'always'],
    'object-curly-spacing': ['warn', 'always'],
    'array-bracket-spacing': ['warn', 'never'],
    'keyword-spacing': ['warn', { before: true, after: true }],
    'space-before-blocks': ['warn', 'always'],
    'space-in-parens': ['warn', 'never'],
    'space-infix-ops': ['warn'],
    'space-unary-ops': ['warn', { words: true, nonwords: false }],
    'space-before-function-paren': [
      'warn',
      { anonymous: 'always', named: 'never', asyncArrow: 'always' },
    ],
    'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
    'array-element-newline': ['warn', 'consistent'],
    'padding-line-between-statements': [
      'warn',
      { blankLine: 'always', prev: 'directive', next: '*' },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
    'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
    curly: ['warn', 'multi-line'],
    'operator-linebreak': ['warn', 'before'],
    'linebreak-style': ['warn', 'unix'],

    // off conflicting typescript rules
    '@typescript-eslint/block-spacing': 0,
    '@typescript-eslint/brace-style': 0,
    '@typescript-eslint/comma-dangle': 0,
    '@typescript-eslint/comma-spacing': 0,
    '@typescript-eslint/func-call-spacing': 0,
    '@typescript-eslint/indent': 0,
    '@typescript-eslint/key-spacing': 0,
    '@typescript-eslint/keyword-spacing': 0,
    '@typescript-eslint/lines-around-comment': 0,
    '@typescript-eslint/lines-between-class-members': 0,
    '@typescript-eslint/member-delimiter-style': 0,
    '@typescript-eslint/no-extra-parens': 0,
    '@typescript-eslint/no-extra-semi': 0,
    '@typescript-eslint/object-curly-spacing': 0,
    '@typescript-eslint/padding-line-between-statements': 0,
    '@typescript-eslint/quotes': 0,
    '@typescript-eslint/semi': 0,
    '@typescript-eslint/space-before-blocks': 0,
    '@typescript-eslint/space-before-function-paren': 0,
    '@typescript-eslint/space-infix-ops': 0,
    '@typescript-eslint/type-annotation-spacing': 0,
  },
};
